### ISSUE TITLE
User object does not contain user ID or some similar data

### ISSUE THREAD

**Issue by Kasun002** [AmalCSV/BettingCenter-frontend#33]
**API**  : `/users/login`

**Response** 

`{"success":true,"data":{"message":"Successful login.","jwt":"","userName":"kasun92","expireAt":1645870216,"firstName":"Kasun","lastName":"Abaywardana"}}`

Most of the updating **API'S** Asking **`createdBy`**  attribute

**Comment by AmalCSV** [comment]
fixed .  now it is 
{
    "success": true,
    "data": {
        "message": "Successful login.",
        "jwt": "",
        "id": "2",
        "userName": "WisSan791",
        "expireAt": 1647141858,
        "firstName": "Wisal1",
        "lastName": "Sandeepa"
    }
}

**Comment by Kasun002** [comment]
I will do the necessary FE changes.
